package marco.modelo.pojos;
// Generated Feb 18, 2017 4:04:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Worked generated by hbm2java
 */
public class Worked  implements java.io.Serializable {


     private WorkedId id;
     private Company company;
     private Person person;
     private Date endDate;
     private Integer salary;

    public Worked() {
    }

	
    public Worked(WorkedId id, Company company, Person person) {
        this.id = id;
        this.company = company;
        this.person = person;
    }
    public Worked(WorkedId id, Company company, Person person, Date endDate, Integer salary) {
       this.id = id;
       this.company = company;
       this.person = person;
       this.endDate = endDate;
       this.salary = salary;
    }
   
    public WorkedId getId() {
        return this.id;
    }
    
    public void setId(WorkedId id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }




}


